name: CS 1331 Driver Compressor
run-name: CS 1331 Compression
on: [push]
jobs:
  Compress-Drivers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      - name: Setup Python Environment
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.8
      - name: Execute Compression Script
        run: |
          cd scripts
          python combine.py
      - name: Upload Compression Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: compression-output
          path: |
            Driver.java
